---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: php-k8s
  labels:
    app.kubernetes.io/name: php-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: php-k8s
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-k8s
        app.kubernetes.io/component: web
    spec:
      initContainers:
        - name: setup-shared-files
          command: ["/bin/sh", "-c", "cp -r /app/. /data"]
          image: nickcharlton/php-k8s-single-file:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-files
              mountPath: /data

      containers:
        - image: nickcharlton/php-k8s-single-file:1.0.0
          name: php

        - image: nginx:latest
          name: nginx
          volumeMounts:
            - name: shared-files
              mountPath: /app
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

      volumes:
        - name: shared-files
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
