---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: php-k8s
  labels:
    app.kubernetes.io/name: php-k8s
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: php-k8s
    app.kubernetes.io/component: web
